name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven without tests
        run: mvn clean package -DskipTests

      - name: Rename JAR file
        run: mv target/*.jar target/helloworld-${{ env.PROJECT_VERSION }}.jar
